cicd for nodejs

diff --git a/.github/workflows/node-ci-cd.yml b/.github/workflows/node-ci-cd.yml
--- a/.github/workflows/node-ci-cd.yml
+++ b/.github/workflows/node-ci-cd.yml
@@ -46,4 +46,9 @@ jobs:
       - name: Deploy to Server
         run: |
           cd $GITHUB_WORKSPACE/node-webapp-githubactions
-          pm2 restart
+          if pm2 restart index.js; then
+            echo "Application restarted successfully."
+          else
+            echo "Failed to restart the application."
+            exit 1
+          fi
